Portfolio skeleton project/ Work section
RichardChileya/my-portfolio pull request #2
Opened 2022-08-18 20:12 UTC by RichardChileya

## In this section we: 

- I worked on the work section on the page 
- I added 3 work sections on the design page
- I added an about me section 
- Updated the readme file as the code has been updated

2022-08-18 23:19 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @RichardChileya :wave:

### Highlights :1st_place_medal:
 
:heavy_check_mark: Meaningful commits
:heavy_check_mark: Added .gitignore
:heavy_check_mark: Following Github Flow

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional Suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. Otherwise reach out to me on slack which is more fast. You can reach out to me on slack by searching my name in **full-time-students** channel :+1:

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 23:19 UTC, HAMMAS-SALEEM commented on index.html
> +    </section>
- [x] All these cards means `section` tags should be wrapped by a parent `section` tag to follow the 
[HTML semantic](https://www.w3schools.com/html/html5_semantic_elements.asp) tags :+1:
- [x] You also need to use **grid** in the parent `section` tag to align the items :+1:

2022-08-18 23:19 UTC, HAMMAS-SALEEM commented on index.html
> +          <h2 class="lets-connect">LET’S CONNECT</h2>
- [ ] Please use `h3`-`h6` here instead of `h2` because you have already used `h2` in this section. You can also visit the [heading hierarchy](https://www.w3.org/WAI/test-evaluate/preliminary/#headings) which is really good for SEO purpose :+1:

2022-08-18 23:19 UTC, HAMMAS-SALEEM commented on index.html
> +      </div>
- [ ] You should wrap languages, frameworks, technologies using `ul` and `li` tags instead of `div` tags for SEO purpose :thinking:

2022-08-18 23:19 UTC, HAMMAS-SALEEM commented on index.html
> +    </section>
### Your Card
![student-desing (copy)](https://user-images.githubusercontent.com/93039359/185508942-eca3d611-d3d3-42d7-8de1-edf66566a08b.png)

### Figma Card
![FIGMA](https://user-images.githubusercontent.com/93039359/185509872-85a11467-f08f-4e54-b20a-b528fb73c76b.png)


- [ ] You can see that your design is not very similar to the Figma template :thinking:
- [ ] You can see the purple boxes are showing the right position for the contents
- [ ] You can see the orange boxes shows that styling is not very similar to the Figma template
**Please make all these changes so your design will look so much similar to the Figma template :+1:**

2022-08-18 23:19 UTC, HAMMAS-SALEEM commented on index.html
> +      </div>
- [ ] Instead of using `div` tags for language list please use `ul` and `li` tags due to some SEO purpose :+1:

2022-08-18 23:19 UTC, HAMMAS-SALEEM commented on index.html
> +          <h2 class="lets-connect">LET’S CONNECT</h2>
### Your About me Section
![contact (copy)](https://user-images.githubusercontent.com/93039359/185511043-35b07b78-c8ff-4ea3-bac3-78ebd7fb52df.png)

### Figma About me Section
![FIGMA2](https://user-images.githubusercontent.com/93039359/185511062-40df4b4f-947b-4cbc-874c-6f246c723528.png)


- [ ] You can see that red boxes shows that desiging is not very similar to the Figma tempate.
- [ ] You can see that purple boxes shows the right position for the contents :thinking:

**Please make these changes to make your project look like Figma template means professional :+1:**

2022-08-18 23:19 UTC, HAMMAS-SALEEM commented on index.html
> +
### Your button
![button](https://user-images.githubusercontent.com/93039359/185511237-863a9954-d74c-468f-96bc-7e869463bb1d.png)

### Figma Effects
![button-effects](https://user-images.githubusercontent.com/93039359/185511252-026a95ae-cc10-4e83-9c88-e1adcf72a37e.png)

- [ ] All you buttons should have hover, pressed styling shown in the Figma template :+1: to make it look professional :thinking:

2022-08-18 23:19 UTC, HAMMAS-SALEEM commented on README.md
>  # Project Name: Portfolio Skeleton Project
- [ ] Please add a link to license file in your readme to make it easily accessible to other people :+1:

2022-08-19 15:10 UTC, aimemalaika approved these changes
Hi @RichardChileya , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 15:44 UTC, RichardChileya commented
**##Merge Work Section** 

- Updated Work Section 
- Updated Style.css 
- Included updated read-me file

2022-08-19 15:44 UTC, merged